# Numpy Practice Questions

In [12]:
import pandas as pd
import numpy as np

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [21]:
#Create Array A and B
arrayA = np.array([1, 14, 51, 4, 19,19, 81, 0 ])
arrayB = np.array([19, 19, 8,10, 11, 4, 5, 14])
# Stack A and B vertically
npt1_vstack = np.vstack((arrayA, arrayB))
# Stack A and B horizontally
npt1_hstack = np.hstack((arrayA, arrayB))

print("Stacked Vertically:")
print(npt1_vstack)

print("\nStacked Horizontally:")
print(npt1_hstack)


Stacked Vertically:
[[ 1 14 51  4 19 19 81  0]
 [19 19  8 10 11  4  5 14]]

Stacked Horizontally:
[ 1 14 51  4 19 19 81  0 19 19  8 10 11  4  5 14]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [22]:
# Find the intersection using the intersection method
setA = {1, 14, 51, 4, 19, 19, 81, 0}
setB = {19, 19, 8,10, 11, 4, 5, 14}
npt2_intersection = setA.intersection(setB)

print("The intersection between set A and B is:", npt2_intersection)

The intersection between set A and B is: {19, 4, 14}


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [27]:
# Specify the range
min_value = 19
max_value = 81

range_result = {x for x in setA if min_value <= x <= max_value}

print("Numbers in Set A within the range [{}, {}]: {}".format(min_value, max_value, range_result))


Numbers in Set A within the range [19, 81]: {81, 19, 51}


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [37]:
urlt4 = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' 
iris_2d = np.genfromtxt(urlt4, delimiter=',', dtype='float', usecols=[0,1,2,3])
number_mask = (iris_2d [:, 0] < 5.0) & (iris_2d [:, 2] > 1.5)
filtered_iris_2d = iris_2d[number_mask]
filtered_iris_2d


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

# Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).


In [13]:
task1 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
task1.head(100)
#for every 20th row starting from 1st row (index 0, 19, 38, 57, 76)
select1 = ['Manufacturer','Model','Type']
task1m1 = task1[select1]
t1filter = [19, 38, 57, 76] 
task1m2 = task1m1.iloc[t1filter]
task1m2

Manufacturer       Model     Type
19            NaN    Concorde    Large
38            Geo       Metro    Small
57  Mercedes-Benz        190E  Compact
76        Pontiac  Bonneville    Large

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.



In [14]:
task2 = task1
task2.head()



Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

3. How to get the rows of a dataframe with row sum > 100?

In [16]:
task3 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
t3_sums = task3.sum(axis=1)
task3F = task3[t3_sums>100]
task3F

0   1   2   3
0   38  22  31  23
1   28  27  27  38
4   21  39  34  18
5   25  20  29  31
6   39  35  36  26
8   26  25  37  14
10  35  36  37  16
11  33  24  25  19
14  31  33  34  16